version: '3.8'
services:
  kestra:
    image: kestra/kestra:latest
    ports:
      - 8080:8080
    environment:
      - KESTRA_CONFIGURATION={"runners":{"local":{"enabled":true}},"database":{"type":"h2"}}
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
